# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2019
# Author(s): Giulio Benetti <giulio.benetti@benettiengineering.com>
# Copyright (C) 2023 Emcraft Systems

obj-y	:= imxrt1170-evk.o \
	flexspi_cb.o
