# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2019
# Author(s): Giulio Benetti <giulio.benetti@benettiengineering.com>
# Copyright (C) 2023 Emcraft Systems
# Author(s): Vladimir Skvortsov <vskvortsov@emcraft.com>

obj-y	:= imxrt1050-evk.o
obj-$(CONFIG_FSPI_BOOT) += flexspi_cb.o
